name: Sync Default Branch
on:
  push: { branches: main }
  workflow_dispatch:
permissions: {}

jobs:
  sync-default-branch:
    if: github.ref_name == github.event.repository.default_branch
    permissions: {contents: write}
    runs-on: ubuntu-latest
    steps:
    - uses: step-security/harden-runner@v2
      with: {egress-policy: audit}
    - uses: actions/checkout@v6
    - run: git push --force origin HEAD:refs/heads/master

# One-time commands for users to switch-over:
#
# ```console
# git branch -m master main
# git fetch origin
# git branch -u origin/main main
# git remote set-head origin -a
# ```
